### ISSUE TITLE
add python format to qulacs_format.sh

### ISSUE THREAD

**Issue by herring101** [Qulacs-Osaka/qulacs-docker-images#8]
qulacsの方でpythonのフォーマットも実行したいです。
`qulacs_format.sh`に
```sh
find $PROJECT/benchmark $PROJECT/pysrc $PROJECT/python -regex '.*\.py' -exec black --line-length 79
```
を追加をしようと思っています。
shellの書き方に詳しくないので間違ってたら教えてください

**Comment by Hiroya-W** [comment]
findを使って`*.py`を検索せずとも、blackにフォーマットを適用したいファイルが含まれているディレクトリ名を渡すことで、black自身で再帰的に検索ができるかもしれません。例えばこのような感じです。検証が十分に出来ていないため、よければ試してみてほしいです。

```
black $PROJECT/benchmark $PROJECT/pysrc $PROJECT/python
```

また、`--line-length 79`のようなオプションは、プロジェクト内の `pyproject.toml`内に設定として記述することも可能です。
https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format

これらを組み合わせれば、メンテナンスしやすいコマンドを用意できるかもしれません。
